name: TeamAdvantage
main: com.github.CubieX.TeamAdvantage.TeamAdvantage
author: CubieX
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit]
version: 0.1.1
description: Gives teams of players some bonus

commands:
    ta:
      description: Using TeamAdvantage
      usage: /ta list [team] | create <teamName> | delete <teamName> | remove <player> 
             | invite <player> | uninvite <player> | request <teamName> | unrequest <teamname>
             | clear <teamname> | version | reload

permissions:
    teamadvantage.use:
        description: Allows using the plugin
        default: op
    teamadvantage.admin:
        description: Allows full control
        default: op
        children:
          teamadvantage.use: true