name: TeamAdvantage
main: com.github.CubieX.TeamAdvantage.TeamAdvantage
author: CubieX
depend: [Vault]
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit]
version: 0.4.3
description: Gives teams of players bonus effects

commands:
    ta:
      description: Using TeamAdvantage
      aliases: [team]
      usage: /ta help | version | reload

permissions:
    teamadvantage.use:
        description: Allows using the plugin
        default: op
    teamadvantage.admin:
        description: Allows full control
        default: op
        children:
          teamadvantage.use: true