##########
# General
##########
# do NOT change the config version!
config_version: 1
# set locale for user dialog messages
language: de
# enable debug output
debug: false
# Notification delay in minutes to notify team leaders and players
# of pending requests and invitations (1-60)
notificationDelay: 10
#
####################
# Gameplay settings
####################
# Worlds to allow team PvP (also enables 'hostile team members in world' notification)
pvpWorlds:
  - world
#
##########
# Effects
##########
# Should explosions cause block damage?
doBlockDamage: false
#
# Max distance from other team members to gain bonus effects (1-100)
maxBonusEffectsActivationDistance: 10
#
###################
# Economy settings
###################
# Currency symbol or name (singular)
currencySingular: '$'
#
# Currency symbol or name (plural)
# Set this to the same symbol as the singular entry if only a symbol like '$' is used
# instead of a name like "Dollar"
currencyPlural: '$'
#
# Costs for creating a team (0 - 100,000)
costsCreateTeam: 0
#
# Cycle time in DAYS to charge the
# costsPerMemberPerTeamFeeCycle from team account (0 - 365)
# Set to 0 to deacivate the fee.
teamFeeCycle: 0
#
# Fee for each member of a team per teamFeeCycle (0 - 100,000)
costsPerMemberPerTeamFeeCycle: 0
#
# Costs for setting a new team home point (0 - 100,000)
costSetTeamHome: 0
#
################
# Bonus effects
################
# List of available bonus effects. See wiki on github for full explanation or
# ingame help.
#
# comment out unwanted effects with # (all sub key also!)
# Price is per duration.
# price is an integer and goes from 0 - 1000000.
# Duration can be given in days (d), hours (h), minutes (m) or seconds (s)
# from 1s - 3600d. The unit is exclusive. You can only use ONE per effect.
# e.g. '1d' is valid while '1d 5m' is not.
#
bonusEffects:
  EXPARR:
    price: 0
    duration: 1m
  DBOOST:
    price: 0
    duration: 1m
  PARMOR:
    price: 0
    duration: 1m