# do NOT change the config version!
config_version: 1
# set locale for user dialog messages
language: de
# enable debug output
debug: false
# Notification delay in minutes to notify team leaders and players
# of pending requests and invitations (1-60)
notificationDelay: 10
# Should explosions cause block damage?
doBlockDamage: false
#
# Economy settings
#
# Currency symbol or name (singular)
currencySingular: '$'
# Currency symbol or name (plural)
# Set this to the same symbol as the singular entry if only a symbol like '$' is used
# instead of a name like "Dollar"
currencyPlural: '$'
# Costs for creating a team (0 - 100,000)
costsCreateTeam: 0
# Costs for affiliating a member into a team (0 - 100,000)
costsAffiliateMember: 0 
# 